
# Group Foos

## /foos/{key}

+ Parameters
    + key: `ABeeSee` (string)

### Get Foo [GET]
github.com/cormoran/test2doc/example/mux/foos.GetFoo

+ Response 200 (application/json)



    + Body

            {
                "B": "A",
                "A": "Bee",
                "R": "See"
            }        



## /foos{?n}

+ Parameters
    + n: `10` (number)

### Get Foos [GET]
github.com/cormoran/test2doc/example/mux/foos.GetFoos

+ Response 200 (application/json)



    + Body

            {
                "2": {
                    "B": "",
                    "A": "",
                    "R": "2"
                },
                "ABeeSee": {
                    "B": "A",
                    "A": "Bee",
                    "R": "See"
                },
                "OneTwoThree": {
                    "B": "One",
                    "A": "Two",
                    "R": "Three"
                },
                "SomethingFunForYou": {
                    "B": "Something",
                    "A": "Fun",
                    "R": "ForYou"
                }
            }        


